### ISSUE TITLE
Multirom manager app

### ISSUE THREAD

**Issue by Djmattox08** [multirom-nexus6p/multirom#2]
when I installed the multirom installer app, it's telling me that I don't have the multi rom recover installed even though it is installed and working correctly.

**Comment by npjohnson** [comment]
This is an ongoing (and valid) bug. I will contact Tassadar about this soon (either we aren't setting a flag we should be, or the app isn't set to check for our naming conventions).

**Comment by zhuowei** [comment]
@npjohnson I haven't looked at this closely so I'm not sure if this is causing it, but our recovery images don't have version set internally; I have no idea why. This also breaks version autodetect when generating manifests (I worked around that, but I guess MultiROMMgr requires it)

Check Tassadar's manifest generator in bugfree-tribble to see where the version numbers are?

**Comment by zhuowei** [comment]
@npjohnson we need to label recoveries with https://github.com/Tasssadar/bugfree-tribble/blob/master/mrom_recovery_release.sh it seems.

**Comment by npjohnson** [comment]
I'll get to this soon.

**Comment by npjohnson** [comment]
Fixed by overhauling mrom_recovery_release.sh and adding to my local build process. I plan on simplifying this all later, but for now, the script will only likely work on my machine without file path edits.

Relevant Commit to the scripts repo: https://github.com/multirom-nexus6p/bugfree-tribble/commit/98a91c6d0984625a8ce6cade29a67ab5d698f0da

**Comment by jollaman999** [comment]
You can also do this with AIK(Android Image Kitchen) tool.
Add 'mrom-YYYYMMDD-00' to split_img/recovery.img-board.

**Comment by npjohnson** [comment]
This is now actually fixed.
