### ISSUE TITLE
Android pay

### ISSUE THREAD

**Issue by Steapa** [multirom-nexus6p/multirom#3]
Had Pay working on beta 1 with stock unrooted imgs as primary but not now on Beta 4 clean install. Reported in XDA thread.

**Comment by zhuowei** [comment]
@Steapa I don't think anything changed between beta 1 and beta 4 that would break Pay: Is Verity still enabled? (When you boot the device does it show an orange "cannot be verified" or a red "system is corrupt"?)

For what it's worth, I'm running the Beta 1 multirom with the Beta 2 kernel and I'm passing https://play.google.com/store/apps/details?id=com.cigital.safetynetplayground&hl=en. Can you please check what result you get from that app?

**Comment by npjohnson** [comment]
Here's the thing, as I described on XDA, it isn't this breaking your SafetyNet check (the check AP relies on), its something else. Likely some .zip modified your system in a way that's nuking SafetyNet.

I just tried on the March Factory Image, un-rooted, with MR, and AP works fine.
