### ISSUE TITLE
MultiROM not working

### ISSUE THREAD

**Issue by akshaysalunke13** [multirom-nexus6p/multirom#4]
I have installed MultiROM with primary stock(MMB29Q) with provided modified kernel and i flased CM as secondary ROM.But I do not get the ROM selection menu and I am directly booted into primary ROM.I have tried injecting to current bootsector several times.

**Comment by zhuowei** [comment]
@akshaysalunke13 this is a known issue with encrypted storage and is fixed in stable 2 - we're testing it right now and will upload it soon.

**Comment by metalcated** [comment]
Same here and great news! I'll test! ;-) metalcated on xda

**Comment by stephendore** [comment]
Pardon my potential ignorance, but isn't the Nexus 6P storage encrypted by default?
And if that's the case, how has anyone gotten MultiROM working on it thus far?

**Comment by npjohnson** [comment]
Fixed.

**Comment by zhuowei** [comment]
@stephendore this was a regression (Beta 1 and 4 had working encryption support).
