### ISSUE TITLE
Recovery does not support Android N encryption

### ISSUE THREAD

**Issue by deltaryz** [multirom-nexus6p/multirom#8]
The recovery hangs at splashscreen on boot with N-based roms

This has already been fixed in https://dl.twrp.me/angler/twrp-3.0.2-1-angler.img.html - the MultiROM recovery needs to be updated to follow suit. Support for Nougat decryption seems to be the only change in this version.

Currently, in order to flash zips to N-based roms, one must flash an older vendor.img in fastboot, flash the zips in TWRP, then return to fastboot and flash the current vendor.img before booting the system.

**Comment by deltaryz** [comment]
Closed to move issue to the recovery's repo, but there is no issue tracker there. Sorry if this was annoying

**Comment by npjohnson** [comment]
I fixed it. Release should be by the end of October
