### ISSUE TITLE
Can't sideload android 7 zip

### ISSUE THREAD

**Issue by MiniDigger** [multirom-nexus6p/multirom#9]
log on pc: 
error: protocol fault (no status)
log on device:
you need adb 1.0.32 or newer to sideload to this device

**Comment by deltaryz** [comment]
Have you tried using adb 1.0.32 or newer? Make sure you're up to date using the SDK manager, or get it from https://developer.android.com/studio/index.html under "get just the command line tools".

**Comment by MiniDigger** [comment]
Sorry, after carefully reading the message I did that, but updating took to long and I went to bed. Will try again when I get home, leaving this open till I can confirm that it is fixed.

**Comment by MiniDigger** [comment]
turns out I had multiple adb installations and it was picking an old adb version. 
so I fixed my path and tried it with 1.0.36. that at least started this time.
now I get an error while installing (on device) 
after "Patching system unconditionally..." a see two lines "E:unknown command [log]" and a message telling me that the update of the system image failed.  (screenshot http://i.minidigger.me/2016/10/chrome_05_22-41-51.png)
the image I was trying to install was 7.0.0 (NBD90X) from the  google site https://developers.google.com/android/nexus/ota
my multirom version is v33, my recovery is 2016-05-28 (0) and my kernel stock 6.0.1-20160514

**Comment by npjohnson** [comment]
This is an Android N related edify issue I fixed. Release should be by the end of October

**Comment by MiniDigger** [comment]
~~any news on this?~~

nvm., just saw your post from yesterday in the xda thread.
